src/Form/HangoutType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use App\Entity\Hangout;
use App\Entity\Location;
use App\Entity\State;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HangoutType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('startingDateTime', DateType::class, ['widget' => 'single_text', 'format' => 'yyyy-MM-dd'])
            ->add('lastSubmitDate', DateType::class, ['widget' => 'single_text', 'format' => 'yyyy-MM-dd'])
            ->add('length', TimeType::class, ['widget' => 'single_text', 'attr' => ['step' => '900', 'min' => '00:30', 'max' => '12:00', 'value' => '01:00']])
            ->add('maxParticipant')
            ->add('detail', TextareaType::class, ['required' => false, 'attr' => ['rows' => '2']]);

        if ($options['is_admin']) {
            $builder->add('campus', EntityType::class, [
                'class' => Campus::class,
                'choice_label' => 'name',
            ]);
        }

        $builder
            ->add('location', EntityType::class, [
                'class' => Location::class,
                'choice_label' => 'name',
            ])
            ->add('save', SubmitType::class,
                ['label' => 'Enregistrer'])
            ->add('publish', SubmitType::class,
                ['label' => 'Publier'])
            ->add('delete', SubmitType::class,
                ['label' => 'Supprimer']);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Hangout::class,
            'is_admin' => false,
        ]);
    }
}

src/Form/Models/FiltresModel.php
<?php

namespace App\Form\Models;

use App\Entity\Campus;
use App\Entity\State;

use Symfony\Component\Validator\Constraints as Assert;


class FiltresModel
{
    private ?Campus $campus = null;
    private ?string $name = null;
    #[Assert\LessThanOrEqual(propertyPath: "end", message: 'La date de début ne peut pas dépasser la date de fin !')]
    private ?\DateTimeInterface $start = null;

    #[Assert\GreaterThanOrEqual(propertyPath: "start", message: 'La date de fin ne peut pas être antérieure à la date de début !')]
    private ?\DateTimeInterface $end = null;

    private ?State $state = null;

    private bool $isOrganizer = false;
    private bool $isRegistered = false;
    private bool $isNotRegistered = false;
    private bool $isPast = false;


    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): void
    {
        $this->campus = $campus;
    }


    public function isNotRegistered(): bool
    {
        return $this->isNotRegistered;
    }

    public function setIsNotRegistered(bool $isNotRegistered): void
    {
        $this->isNotRegistered = $isNotRegistered;
    }

    public function isOrganizer(): bool
    {
        return $this->isOrganizer;
    }

    public function setIsOrganizer(bool $isOrganizer): void
    {
        $this->isOrganizer = $isOrganizer;
    }

    public function isPast(): bool
    {
        return $this->isPast;
    }

    public function setIsPast(bool $isPast): void
    {
        $this->isPast = $isPast;
    }

    public function isRegistered(): bool
    {
        return $this->isRegistered;
    }

    public function setIsRegistered(bool $isRegistered): void
    {
        $this->isRegistered = $isRegistered;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(?\DateTimeInterface $start): void
    {
        $this->start = $start;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(?\DateTimeInterface $end): void
    {
        $this->end = $end;
    }

    public function getState(): ?State
    {
        return $this->state;
    }

    public function setState(?State $state): void
    {
        $this->state = $state;
    }

    /**
     * @Assert\Callback
     */
    public function validateExclusiveFilters(ExecutionContextInterface $context)
    {
        $countFilled = 0;

        // Booléens
        $bools = [
            $this->isOrganizer,
            $this->isRegistered,
            $this->isNotRegistered,
            $this->isPast,
        ];

        $countFilled += count(array_filter($bools, function($v) {
            return $v === true;
        }));

        // Champs de sélection / entités
        $countFilled += $this->campus !== null ? 1 : 0;
        $countFilled += $this->state !== null ? 1 : 0;

        // Champs texte
        $countFilled += !empty(trim((string)$this->name)) ? 1 : 0;

        // Dates
        $countFilled += $this->start !== null ? 1 : 0;
        $countFilled += $this->end !== null ? 1 : 0;

        if ($countFilled > 1) {
            $context->buildViolation('Vous ne pouvez sélectionner ou remplir qu\'un seul filtre à la fois.')
                ->addViolation();
        }
    }

}

src/Controller/HangoutController.php
<?php

namespace App\Controller;

use App\Entity\Hangout;
use App\Entity\Location;
use App\Entity\State;
use App\Entity\User;
use App\Form\FilterHangoutType;
use App\Form\HangoutType;
use App\Form\Models\FiltresModel;
use App\Form\PlaceType;
use App\Repository\HangoutRepository;
use App\Repository\StateRepository;
use App\Repository\UserRepository;
use App\Utils\HangoutService;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use function PHPUnit\Framework\throwException;


#[Route('/hangouts', name: 'hangout_')]
final class HangoutController extends AbstractController
{

    public function __construct(
        private readonly StateRepository        $stateRepository,
        private readonly HangoutRepository      $hangoutRepository,
        private readonly EntityManagerInterface $entityManager,
        private readonly ValidatorInterface     $validator,
    )
    {
    }


    #[Route('/{page}', name: 'list', requirements: ['page'=>'\d+'])]
    public function listHangouts(Request $request, int $page = 1): Response
    {

        /**
         * @var User $user
         */
        $user = $this->getUser();
        $filtersModel = new FiltresModel();//permet de mapper les données directement atravers le model
        if (!$user) {
            // Gère le cas utilisateur non connecté (redirige, exception, etc.)
            throw $this->createAccessDeniedException('Vous devez être connecté');
        }


        //creation du form - et je lui passe le model
        $filterForm = $this->createForm(FilterHangoutType::class, $filtersModel);
        $filterForm->handleRequest($request);


        $hangouts = $this->hangoutRepository->findFilteredEvent($user, $filtersModel, $page);

        //        dump($filtersModel, $hangouts, $filtersModel->getCampus());

        $totalHangout = $this->hangoutRepository->count();
        $maxPages =ceil($totalHangout / Hangout::HANGOUT_PER_PAGE);

            if ($page < 1) {
                return $this->redirectToRoute('hangout_list', ['page' => 1]);
            }
            if ($page > $maxPages) {
                return $this->redirectToRoute('hangout_list', ['page' => $maxPages]);
            }

        return $this->render('hangout/list.html.twig', [
            'hangouts' => $hangouts,
            'filterForm' => $filterForm,
            'currentPage' => $page,
            'maxPages' => $maxPages,
        ]);
    }


    #[Route('/detail/{id}', name: 'detail', requirements: ['id' => '\d+'])]
    public function detailHangout(int $id): Response
    {
        $hangout = $this->hangoutRepository->find($id);

        if (!$hangout) {
            throw $this->createNotFoundException("La sortie n'existe pas.");
        }

        return $this->render('hangout/detail.html.twig', [
            'hangout' => $hangout
        ]);
    }

    #[Route('/add', name: 'add')]
    public function addHangout(Request $request): Response
    {
        /**
         * @var User $user
         */
        $user = $this->getUser();


        $hangout = new Hangout();
        $place = new Location();
        $form = $this->createForm(HangoutType::class, $hangout, [
            'is_admin' => $this->isGranted('ROLE_ADMIN'),
        ]);

        $formPlace = $this->createForm(PlaceType::class, $place, [
            'action' => $this->generateUrl('places_add')
        ]);

        $form->handleRequest($request);
        $formPlace->handleRequest($request);

        $request->query->get('cancelMotif', 'not_existing');

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('save')->isClicked()) {
                $hangout->setState($this->stateRepository->findOneBy(['label' => 'CREATE']));
            } elseif ($form->get('publish')->isClicked()) {
                $hangout->setState($this->stateRepository->findOneBy(['label' => 'OPEN']));
            }
            if (!$this->isGranted('ROLE_ADMIN')) {
            $hangout->setCampus($user->getCampus());
            }
            $hangout->setOrganizer($user);
            $this->entityManager->persist($hangout);
            $this->entityManager->flush();
            $this->addFlash("success", "Sortie " . $hangout->getName() . " ajoutée");

            return $this->redirectToRoute('hangout_detail', ['id' => $hangout->getId()]);
        }

        return $this->render('hangout/add.html.twig', [
            'formHangout' => $form,
            'formPlace' => $formPlace,
        ]);
    }

    #[IsGranted('POST_MODIFY', 'hangout')]
    #[Route('/modify/{id}', name: 'modify', requirements: ['id' => '\d+'])]
    public function modifyHangout(Request $request, Hangout $hangout): Response
    {

        $place = new Location();

        $form = $this->createForm(HangoutType::class, $hangout, [
            'is_admin' => $this->isGranted('ROLE_ADMIN'),
        ]);
        $formPlace = $this->createForm(PlaceType::class, $place, [
            'action' => $this->generateUrl('places_add')
        ]);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($form->get('delete')->isClicked()) {
                $this->entityManager->remove($hangout);
                $this->entityManager->flush();
                $this->addFlash('success', "Sortie ".$hangout->getName()." supprimée avec success");
                return $this->redirectToRoute('hangout_list', ['id' => $hangout->getId()]);
            } elseif ($form->get('save')->isClicked()) {
                $this->entityManager->persist($hangout);
                $this->entityManager->flush();

                $this->addFlash("success", "Sortie mise a jours !");
                return $this->redirectToRoute('hangout_detail', ['id' => $hangout->getId()]);
            } elseif ($form->get('publish')->isClicked()) {
                $hangout->setState($this->stateRepository->findOneBy(['label' => 'OPEN']));
                $this->entityManager->persist($hangout);
                $this->entityManager->flush();

                $this->addFlash("success", "Sortie publiée!");
                return $this->redirectToRoute('hangout_detail', ['id' => $hangout->getId()]);
            }

        }
        return $this->render('hangout/modify.html.twig', [
            'formUpdate' => $form,
            'formPlace' => $formPlace,
            'hangout' => $hangout,
        ]);
    }

    #[isGranted('POST_PUBLISH', 'hangout')]
    #[Route('/publish/{id}', name: 'publish', requirements: ['id' => '\d+'])]

    public function publishHangout(Request $request, Hangout $hangout, StateRepository $stateRepository): Response
    {
        $hangout = $this->hangoutRepository->find($hangout->getId());
        $state = $stateRepository->findOneBy(['label' => 'OPEN']);

        if (!$hangout) {
            throw $this->createNotFoundException("La sortie n'existe pas.");
        }
        if ($hangout->getState()->getLabel()==="CREATE") {
            $hangout->setState($state);
        }

        $violations = $this->validator->validate($hangout);
        if (count($violations) > 0) {
            foreach ($violations as $violation) {
                $this->addFlash('danger', $violation->getMessage());
            }
        } else {
            $this->entityManager->persist($hangout);
            $this->entityManager->flush();
            $this->addFlash('success', "la sortie ".$hangout->getName()." a été publiée");
            return $this->redirectToRoute('hangout_list');
        }
        return $this->render('hangout/detail.html.twig', [$hangout->getId()]);
    }


    #[ISGranted('POST_CANCEL', 'hangout')]
    #[Route('/cancel/{id}', name: 'cancel', requirements: ['id' => '\d+'])]
    public function cancelHangout(
        int                    $id,
        Request                $request,
        Hangout $hangout,
        EntityManagerInterface $entityManager,
        HangoutRepository      $hangoutRepository,
        StateRepository        $stateRepository
    ): Response
    {
        $hangout = $hangoutRepository->find($id);
        $state = $stateRepository->findOneBy(['label' => 'CANCELLED']);
        $dateNow = new DateTimeImmutable();

        if (!$hangout) {
            throw $this->createNotFoundException("Hangout not found");
        }
        if ($request->isMethod('POST')) {

            if ($hangout->getStartingDateTime() < $dateNow) {
                $this->addFlash('', "la sortie " . $hangout->getName() . " a déjà commencé, elle ne peut pas être annulée");
                return $this->redirectToRoute('hangout_detail', ['id' => $hangout->getId()]);
            } else {
                $cancelMotif = $request->request->get('cancelMotif', null);
                $hangoutDetail = $hangout->getDetail();
                $hangout->setDetail($hangoutDetail . '. Annulé : ' . $cancelMotif);
                $hangout->setState($state);
                $this->entityManager->persist($hangout);
                $this->entityManager->flush();
                $this->addFlash('success', "Sortie " . $hangout->getName() . " cancelled");

                return $this->redirectToRoute('hangout_detail', ['id' => $hangout->getId()]);
            }
        }

        return $this->render('hangout/cancel.html.twig', [
            'hangout' => $hangout
        ]);

    }

    #[isGranted('POST_SUBSCRIBER', 'hangout')]
    #[Route('/subscribe/{id}', name: 'subscribe', requirements: ['id' => '\d+'])]

    public function subscribeToHangout(int $id, Hangout $hangout): Response

    {
        $hangout = $this->hangoutRepository->find($id);
        /**
         * @var User $user

templates/hangout/add.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <style>

.modal {
    display: none; /* hidden by default */
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.6); /* semi-transparent black */
    z-index: 1000;

    align-items: center;
    justify-content: center;
}

.modal.show {
    display: flex;
}

.modal-content {
    background: #fff;
    padding: 20px;
    border-radius: 10px;
    min-width: 300px;
    max-width: 600px;
    box-shadow: 0 5px 20px rgba(0,0,0,0.3);
    position: relative;
}

.modal-close {
    position: absolute;
    top: 10px;
    right: 15px;
    background: none;
    border: none;
    font-size: 1.5rem;
    cursor: pointer;
}

main ul {

    border-radius: 4px;
    border: 1px solid #9e473b;
    padding: 4px 6px ;
}
main ul > li {
    color: #9e473b;
    list-style: none;

}
main ul > li::before {
    content: '⚠';
}

.btn-delete {
    background: #e74c3c ;
    border: 1px solid #e74c3c ;
}

.btn-publish {
    background: #1b9448 ;
    border: 1px solid #1b9448 ;
}

.btn-add-location {
    background: #5c636a ;
    border: 1px solid #5c636a;
}
</style>
{% endblock %}
{% block title %}
    Ajouter une sortie |
    {{ parent() }}
{% endblock %}
{% block body %}
    <div class="container">
        <h2>Ajouter une sortie!</h2>
        <section class="grid">
            <div>
                {{ form_start(formHangout) }}
                {{ form_row(formHangout.name) }}
                {{ form_row(formHangout.startingDateTime) }}
                {{ form_row(formHangout.lastSubmitDate) }}
                {{ form_row(formHangout.detail) }}
            </div>
            <div>
                {% if is_granted('ROLE_ADMIN', app.user) %}
                {{ form_row(formHangout.campus) }}
                {% endif %}
                {{ form_row(formHangout.length) }}
                {{ form_row(formHangout.maxParticipant) }}
                {{ form_label(formHangout.location) }}
                <div class="grid">

                    {{ form_widget(formHangout.location) }}

                    <div type="button" id="showModalBtn" class="btn-add-location" onclick="showModal()">Ajouter un lieu</div>
                </div>

                <div class="grid">

                {{ form_row(formHangout.save) }}
                {{ form_row(formHangout.publish, {'attr' : {'class':'btn-publish'}}) }}
                {{ form_row(formHangout.delete, {'attr' : {'class':'btn-delete'}}) }}
                </div>

                {{ form_end(formHangout) }}

                <div id="placeModal" class="modal">
                    <div class="modal-content">
                        <button class="modal-close" type="button">&times;</button>
                        {{ include('places/add.html.twig') }}
                    </div>
                </div>
            </div>
        </section>


    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const modal = document.getElementById('placeModal');
            const openBtn = document.getElementById('showModalBtn');
            const closeBtn = modal.querySelector('.modal-close');

            // Open modal
            openBtn.addEventListener('click', () => {
                modal.classList.add('show');
            });

            // Close modal on button click
            closeBtn.addEventListener('click', () => {
                modal.classList.remove('show');
            });

            // Close modal on outside click
            modal.addEventListener('click', (e) => {
                if (e.target === modal) {
                    modal.classList.remove('show');
                }
            });
        });

    </script>
{% endblock %}

templates/hangout/cancel.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <main class="container">
        <div class="align-content-center">
            <div>
                <h1>Annuler une sortie</h1>
            </div>
            <hr>

            <section>
                <div>
                    <div class="grid">
                        <span>Nom de la sortie :</span>
                        <h6>{{ hangout.name}}</h6>
                    </div>

                    <div class="grid">
                        <span>Date et heure de la sortie :</span>
                        <h6>{{ hangout.startingDateTime | date }}</h6>
                    </div>

                    <div class="grid">
                        <span>Campus :</span>
                        <h6>{{ hangout.campus.name }}</h6>
                    </div>

                    <div class="grid">
                        <span>Lieu :</span>
                        <h6>{{ hangout.location.name }}</h6>
                    </div>

                    <div class="grid">
                        <span>Motif :</span>
                        <form action="{{ path('hangout_cancel', {'id': hangout.id}) }}" method="post">
                            <label>
                            <input
                                    type="text" id="cancelMotif" name="cancelMotif">
                            <button onclick="return confirm('Voulez-vous vraiment annuler la sortie {{ hangout.name }}?')" type="submit">Enregistrer</button>
                            </label>
                        </form>
                            <a onclick href="{{ path('hangout_detail', {'id' : hangout.id}) }}">
                                <button>Annuler l'annulation</button>
                            </a>

                    </div>
                </div>

            </section>
        </div>
    </main>



{% endblock %}

{% block title %}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

templates/hangout/list.html.twig
{% extends 'base.html.twig' %}

    {% block stylesheets %}
        {{ parent() }}
        <style>
            .btAdd{
                display: flex;
                justify-content: flex-end;
            }

            @media only screen and (max-width: 768px) {
                .mobile-hide {
                    display: none !important;
                }
                table {
                    font-size: 0.8rem;
                }

                .grid {
                    display: block;
                }

                .checkboxes {
                    margin-top: 1rem;
                }
            }
        </style>
    {% endblock %}

{% block body %}

    <div>

        <details style="background-color: #e2e2e2; padding: 6px; border-radius: 6px;" class="mobile-hide filters accordion"  >
            <summary>Filtres</summary>
            <div style="padding: 6px; border-radius: 6px">
                {{ form_start(filterForm) }}
                <div class="grid">
                    <div>
                        {{ form_row(filterForm.campus) }}
                        {{ form_row(filterForm.name) }}
                        {{ form_row(filterForm.start) }}
                        {{ form_row(filterForm.end) }}
                    </div>
                    <div class="checkboxes">
                        {{ form_row(filterForm.isOrganizer) }}
                        {{ form_row(filterForm.isRegistered) }}
                        {{ form_row(filterForm.isNotRegistered) }}
                        {{ form_row(filterForm.isPast) }}<br>
                        <input type="submit" value="Rechercher">
                    </div>
                </div>
                {{ form_end(filterForm) }}
            </div>
        </details>

        <div class="mobile-hide btAdd">
            <a href="{{ path('hangout_add') }}">
                <button class="outline">Créer une sortie</button>
            </a>
        </div>

        <h2 class="mobile-hide">Résultats des sorties filtrées</h2>

        <table class="overflow-auto">
            <thead>
            <tr>
                <th>Nom de la sortie</th>
                <th class="mobile-hide">Date de la sortie</th>
                <th class="mobile-hide">Clôture</th>
                <th>Inscrits/Places</th>
                <th class="mobile-hide">État</th>
                <th class="mobile-hide">Inscrit</th>
                <th class="mobile-hide">Organisateur</th>
                <th class="mobile-hide">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% if hangouts is empty %}
                <tr>
                    <td colspan="9">Aucune sortie trouvée.</td>

                </tr>
            {% else %}
                {% for hangout in hangouts %}

                     <tr>
                        <td><a href="{{ path('hangout_detail', {'id': hangout.id}) }}"
                               class="contrast no-underline">{{ hangout.name | capitalize }}</a></td>
                        <td>{{ hangout.startingDateTime|date('d M Y') }}</td>
                        <td class="mobile-hide">{{ hangout.lastSubmitDate|date('d M Y') }}</td>
                        <td class="mobile-hide">{{ hangout.subscriberLst|length }} / {{ hangout.maxParticipant }}</td>

                        <td class="mobile-hide" {% if hangout.state.label|upper is same as('CANCELLED') %} style="color: red;" {% endif %}>{{ hangout.state.label | capitalize }}</td>

                         <td class="mobile-hide" style="color: green"> {% if is_granted('POST_SUBSCRIBED', hangout) %}
                                <b>X</b>
                            {% endif %}
                        </td>
                        <td class="mobile-hide">
                            <a href="{{ path('user_detail', {'id': hangout.organizer.id}) }}">{{ hangout.organizer.username }}</a>
                        </td>
                        <td class="mobile-hide">
                            {% set actions = [] %}

                            {% if is_granted('POST_SUBSCRIBER', hangout) %}
                                {% set actions = actions|merge(['<a href="' ~ path('hangout_subscribe', {'id': hangout.id}) ~ '" class="contrast no-underline">S\'inscrire</a>']) %}
                            {% endif %}
                            {% if is_granted('POST_UNSUBSCRIBER', hangout) %}
                                {% set actions = actions|merge(['<a href="' ~ path('hangout_unsubscribe', {'id': hangout.id}) ~ '" class="contrast no-underline">Se désister</a>']) %}
                            {% endif %}
                            {% if not is_granted('POST_MODIFY', hangout) %}
                                {% set actions = actions|merge(['<a href="' ~ path('hangout_detail', {'id': hangout.id}) ~ '" class="contrast no-underline">Afficher</a>']) %}
                            {% endif %}
                            {% if is_granted('POST_MODIFY', hangout) %}
                                {% set actions = actions|merge(['<a href="' ~ path('hangout_modify', {'id': hangout.id}) ~ '" class="contrast no-underline">Modifier</a>']) %}
                            {% endif %}
                            {% if is_granted('POST_CANCEL', hangout) %}
                                {% set actions = actions|merge(['<a href="' ~ path('hangout_cancel', {'id': hangout.id}) ~ '" class="contrast no-underline">Annuler</a>']) %}
                            {% endif %}
                            {% if is_granted('POST_PUBLISH', hangout) %}
                                {% set actions = actions|merge(['<a href="' ~ path('hangout_publish', {'id': hangout.id}) ~ '" class="contrast no-underline">Publier</a>']) %}
                            {% endif %}
                            {{ actions|join(' - ')|raw }}

                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
            </tbody>
        </table>

        <div class="pagination">
            {% if currentPage > 1 %}
                <a href="{{ path('hangout_list', {'page': currentPage - 1}) }}">
                    <button type="button">Précédent</button>
                </a>
            {% endif %}

            <span style="margin: 0 15px;">Page {{ currentPage }} sur {{ maxPages }}</span>

            {% if currentPage < maxPages %}
                <a href="{{ path('hangout_list', {'page': currentPage + 1}) }}">
                    <button type="button" class="outline">Suivant</button>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}